# Generated by Django 6.0 on 2026-03-15 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_shoppingitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingitem',
            name='amount',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='shoppingitem',
            name='preferred_brand',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='shoppingitem',
            name='store',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
