# Generated by Django 6.0 on 2026-03-15 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_shoppingitem_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingitem',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
